### Numpy Drill -- DIY

In [1]:
# Uncomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Create a null vector of size 10

In [2]:
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a vector with values ranging from 10 to 30 

In [3]:
vector_range = np.arange(10, 31)

print(vector_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


#### 4. Reverse a vector (first element becomes last)

In [5]:
vector_range = np.arange(10, 31)

# to reverse which is same as slicing we have

reversed_vector = vector_range[: :-1]

print(reversed_vector)

[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 

In [6]:
matrix = np.arange(9).reshape((3, 3))

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Create a 10x10 array with random values and find the minimum and maximum values

In [9]:
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
[[0.27415961 0.399695   0.64302462 0.51626087 0.3484035  0.05507825
  0.14291096 0.52730183 0.7302613  0.19450233]
 [0.05824158 0.94220821 0.50762317 0.00472717 0.94214535 0.35520972
  0.24419277 0.40137798 0.9481573  0.351641  ]
 [0.87910769 0.82184233 0.73903921 0.51166913 0.60826708 0.09141714
  0.62756786 0.83038343 0.73745725 0.50090494]
 [0.93099399 0.37213691 0.61999116 0.44806277 0.27196589 0.86651141
  0.80258533 0.07494921 0.71772215 0.35682688]
 [0.93549715 0.64088759 0.17530698 0.57847342 0.77935836 0.92502295
  0.23643616 0.34274737 0.74907589 0.16064217]
 [0.56443949 0.15046132 0.49520555 0.65289606 0.47184548 0.74276531
  0.59197834 0.94953387 0.45836722 0.76404719]
 [0.76200192 0.60764146 0.83771073 0.16830131 0.35912077 0.61746507
  0.18692474 0.82254138 0.93976354 0.10380298]
 [0.55129563 0.89961466 0.53866088 0.51769338 0.99481667 0.48400806
  0.84407521 0.85367469 0.06186423 0.96224404]
 [0.66672656 0.77028924 0.95886316 0.34425791 0.22479026 0.5941945

#### 7. Create random vector of size 10 and replace the maximum value by 0

In [13]:
random_vector = np.random.rand(10)

#find the value for the maximum value
max_value = np.argmax(random_vector)

#Replace the maximum value with 0
random_vector[max_value] = 0

# Display the original and replaced vectors
print("Original Random Vector:")
print(random_vector)

Original Random Vector:
[0.13264549 0.17985811 0.49557928 0.08801535 0.         0.36472619
 0.35339901 0.44870495 0.56192674 0.57151969]


#### 8. Create an array and find the most frequent value in the array

In [16]:
an_array = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5, 5])

# Find the most frequent value
most_frequent_value = np.bincount(an_array).argmax()

print("Array:", an_array)
print("Most Frequent Value:", most_frequent_value )

Array: [1 2 2 3 4 4 4 5 5 5 5 5]
Most Frequent Value: 5


#### 9. Find the total value of the elements in the array created in 8

In [18]:
an_array = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5, 5])

#Total value of the above
total_value = np.sum(an_array)

print("Array:", an_array)
print("Total Value:", total_value)

Array: [1 2 2 3 4 4 4 5 5 5 5 5]
Total Value: 45


#### 9. Add 3 to every element of the array created in 8 and find the lowest value in the resulting array

In [19]:
an_array = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5, 5])

# Add 3 to every element
updated_array = an_array + 3

# Find the lowest value in the updated array
lowest_value = np.min(updated_array)

print("Original Array:", an_array)
print("Updated Array:", updated_array)
print("Lowest Value in the Updated Array:", lowest_value)

Original Array: [1 2 2 3 4 4 4 5 5 5 5 5]
Updated Array: [4 5 5 6 7 7 7 8 8 8 8 8]
Lowest Value in the Updated Array: 4


#### 10. Create an array and find the most frequent value in the array

In [23]:
my_array = np.array([3,3,3,4,4,4,5,5,6,6,6,7,7,7,7,7,7,7,8])

# Find the most frequent value
most_frequent_value = np.bincount(my_array).argmax()

print("Array:", my_array)
print("Most Frequent Value:", most_frequent_value )

Array: [3 3 3 4 4 4 5 5 6 6 6 7 7 7 7 7 7 7 8]
Most Frequent Value: 7


The array below represents the distance covered by racers in meters

In [3]:
distance_covered = np.random.randint(200, 550, 30)
#print(distance_covered)

[440 429 203 499 532 338 425 355 399 216 283 500 430 202 207 387 270 280
 416 368 436 360 305 291 349 472 544 285 521 467]


#### 11. What is the average distance covered by the racers? 

In [30]:
distances = [440, 429, 203, 499, 532, 338, 425, 355, 399, 216, 283, 500, 430, 202, 207, 387, 270, 280, 416, 368, 436, 360, 305, 291, 349, 472, 544, 285, 521, 467]

# The average distance
average_distance = np.mean(distances)

print("Distances covered by racers in meters:", distances)
print("Average Distance:", average_distance)

Distances covered by racers in meters: [440, 429, 203, 499, 532, 338, 425, 355, 399, 216, 283, 500, 430, 202, 207, 387, 270, 280, 416, 368, 436, 360, 305, 291, 349, 472, 544, 285, 521, 467]
Average Distance: 373.6333333333333


#### 11. What is the total distance covered in `kilometers`?

In [31]:
distances_in_meters = [440, 429, 203, 499, 532, 338, 425, 355, 399, 216, 283, 500, 430, 202, 207, 387, 270, 280, 416, 368, 436, 360, 305, 291, 349, 472, 544, 285, 521, 467]

# Convert to kilometers
distances_in_kilometers = np.array(distances_in_meters) / 1000

# Calculate total distance in kilometers
total_distance_in_kilometers = np.sum(distances_in_kilometers)

print("Distances covered by racers in meters:", distances_in_meters)
print("Distances covered by racers in kilometers:", distances_in_kilometers)
print("Total Distance in kilometers:", total_distance_in_kilometers)

Distances covered by racers in meters: [440, 429, 203, 499, 532, 338, 425, 355, 399, 216, 283, 500, 430, 202, 207, 387, 270, 280, 416, 368, 436, 360, 305, 291, 349, 472, 544, 285, 521, 467]
Distances covered by racers in kilometers: [0.44  0.429 0.203 0.499 0.532 0.338 0.425 0.355 0.399 0.216 0.283 0.5
 0.43  0.202 0.207 0.387 0.27  0.28  0.416 0.368 0.436 0.36  0.305 0.291
 0.349 0.472 0.544 0.285 0.521 0.467]
Total Distance in kilometers: 11.209000000000001


#### 12. How many meter is covered by the racer with the lowest distance travelled?

In [32]:
distances_in_meters = [440, 429, 203, 499, 532, 338, 425, 355, 399, 216, 283, 500, 430, 202, 207, 387, 270, 280, 416, 368, 436, 360, 305, 291, 349, 472, 544, 285, 521, 467]

# Find the index of the minimum distance
index_of_min_distance = np.argmin(distances_in_meters)
min_distance_covered = distances_in_meters[index_of_min_distance]

print("Distances covered by racers in meters:", distances_in_meters)
print("Minimum Distance Covered in meters:", min_distance_covered)

Distances covered by racers in meters: [440, 429, 203, 499, 532, 338, 425, 355, 399, 216, 283, 500, 430, 202, 207, 387, 270, 280, 416, 368, 436, 360, 305, 291, 349, 472, 544, 285, 521, 467]
Minimum Distance Covered in meters: 202


#### 13. How many racers are included altogether?

In [33]:
distances_in_meters = [440, 429, 203, 499, 532, 338, 425, 355, 399, 216, 283, 500, 430, 202, 207, 387, 270, 280, 416, 368, 436, 360, 305, 291, 349, 472, 544, 285, 521, 467]

# Calculating the total number of racers
total_racers = len(distances_in_meters)

print("Total number of racers:", total_racers)

Total number of racers: 30


#### 14. Given the average time travelled as 85 minutes, callute the speed travelled by the respective racer in `Km/hr`

In [34]:
distances_in_kilometers = [0.44 , 0.429,  0.203,  0.499,  0.532,  0.338,  0.425,  0.355,  0.399,  0.216,  0.283,  0.5, 
 0.43,  0.202,  0.207,  0.387,  0.27,   0.28,   0.416,  0.368,  0.436 , 0.36,   0.305,  0.291, 
 0.349,  0.472,  0.544,  0.285,  0.521,  0.467]

average_time_minutes = 85

# Convert average time to hours
average_time_hours = average_time_minutes / 60

# Calculate speeds for each racer
speeds_kph = np.array(distances_in_kilometers) / average_time_hours

print("Distances covered by racers in kilometers:", distances_in_kilometers)
print("Average Time Traveled in hours:", average_time_hours)
print("Speeds of each racer in Km/hr:", speeds_kph)


Distances covered by racers in kilometers: [0.44, 0.429, 0.203, 0.499, 0.532, 0.338, 0.425, 0.355, 0.399, 0.216, 0.283, 0.5, 0.43, 0.202, 0.207, 0.387, 0.27, 0.28, 0.416, 0.368, 0.436, 0.36, 0.305, 0.291, 0.349, 0.472, 0.544, 0.285, 0.521, 0.467]
Average Time Traveled in hours: 1.4166666666666667
Speeds of each racer in Km/hr: [0.31058824 0.30282353 0.14329412 0.35223529 0.37552941 0.23858824
 0.3        0.25058824 0.28164706 0.15247059 0.19976471 0.35294118
 0.30352941 0.14258824 0.14611765 0.27317647 0.19058824 0.19764706
 0.29364706 0.25976471 0.30776471 0.25411765 0.21529412 0.20541176
 0.24635294 0.33317647 0.384      0.20117647 0.36776471 0.32964706]


#### 15. Which racer travelled with the maximum speed?

In [36]:
# Find the index of the maximum speed
index_of_max_speed = np.argmax(speeds_kph)

print("Speeds of each racer in Km/hr:", speeds_kph)
print("Racer with the maximum speed:", index_of_max_speed)

Speeds of each racer (in Km/hr): [0.31058824 0.30282353 0.14329412 0.35223529 0.37552941 0.23858824
 0.3        0.25058824 0.28164706 0.15247059 0.19976471 0.35294118
 0.30352941 0.14258824 0.14611765 0.27317647 0.19058824 0.19764706
 0.29364706 0.25976471 0.30776471 0.25411765 0.21529412 0.20541176
 0.24635294 0.33317647 0.384      0.20117647 0.36776471 0.32964706]
Racer with the maximum speed: 26


__Create a 2D NumPy array named temperatures representing the daily high temperatures (in Celsius) for a week. The array should have 7 rows (days) and 3 columns (morning, afternoon, evening). Calculate the average temperature for each day and each time slot (morning, afternoon, evening).__

In [37]:
temperatures = np.array([
    [25, 30, 22],
    [28, 32, 24],
    [26, 29, 21],
    [24, 31, 23],
    [27, 33, 25],
    [23, 28, 20],
    [22, 27, 19]
])

# Calculate the average temperature for each day (across columns)
average_daily_temperature = np.mean(temperatures, axis=1)

# Calculate the average temperature for each time slot (across rows)
average_time_slot_temperature = np.mean(temperatures, axis=0)

print("Daily High Temperatures (Celsius):\n", temperatures)
print("\nAverage Temperature for Each Day:\n", average_daily_temperature)
print("\nAverage Temperature for Each Time Slot (Morning, Afternoon, Evening):\n", average_time_slot_temperature)


Daily High Temperatures (Celsius):
 [[25 30 22]
 [28 32 24]
 [26 29 21]
 [24 31 23]
 [27 33 25]
 [23 28 20]
 [22 27 19]]

Average Temperature for Each Day:
 [25.66666667 28.         25.33333333 26.         28.33333333 23.66666667
 22.66666667]

Average Temperature for Each Time Slot (Morning, Afternoon, Evening):
 [25. 30. 22.]
